language:
- objective-c
env:
  matrix:
  - VERSION=2.7.7 NUMPY_VERSION=1.6.0
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION cython wheel six
- cd scikit-image
- python setup.py bdist_wheel
- rename_wheels dist
- pip install dist/*.whl
- cd ..
script:
- pip install --no-index -f $NIPY_WHEELHOUSE nose scipy pillow matplotlib
- if [ "${VERSION:0:3}" != "3.3" ]; then pip install -U numpy; fi
- mkdir tmp_for_test
- cd tmp_for_test
- nosetests --exe -v skimage
- cd ..
before_deploy: cd scikit-image/dist
deploy:
  provider: cloudfiles
  username: jjhelmus
  api-key:
    secure: gPIeSHc1fJ+njTlqGxXAqNpFEqBfzupQFs2YT60dGEFury2pvYDW0O1hdRbuK4Q3D/uokYkFytY7QDBR2s/Mm92rYfUfqKV/qeFD2UhO8ZQ8iaRY2qP4ImbFzzdpq7PlJcoAoolsjroAzO1/NKGhpKj+oRAEnSZW0g+z1ug+g5s=
  region: ORD
  container: wheels
  skip_cleanup: true
